### ISSUE TITLE
API key is visible in the history

### ISSUE THREAD

**Issue by MikeColes** [kotalco/crossover-blacklist#1]
Unknown if the key is valid or not. Comment for #[ebbf511](https://github.com/kotalco/crossover-blacklist/commit/ebbf5111226d61aae35f534821f67eee1d1ac467) is "[feat:remove apiKey](https://github.com/kotalco/crossover-blacklist/commit/ebbf5111226d61aae35f534821f67eee1d1ac467)" The key is still visible if you look at the file history.  

Feel free to drop this issue if it is not a concern. I don't see a security.md or way to mark this issue as private.

**Comment by mohamed-abdelrhman** [comment]
@MikeColes 
this plugin middleware doesn't need an APIKey to work, it's not relevant now coz there is no third party communications
